/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppVideosRouteImport } from './routes/_app.videos'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppGroupsIndexRouteImport } from './routes/_app.groups.index'
import { Route as AppChatsIndexRouteImport } from './routes/_app.chats.index'
import { Route as AppGroupsGroupIdRouteImport } from './routes/_app.groups.$groupId'
import { Route as AppChatsUserIdRouteImport } from './routes/_app.chats.$userId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVideosRoute = AppVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsIndexRoute = AppGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsIndexRoute = AppChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsGroupIdRoute = AppGroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsUserIdRoute = AppChatsUserIdRouteImport.update({
  id: '/chats/$userId',
  path: '/chats/$userId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof AppProfileRoute
  '/videos': typeof AppVideosRoute
  '/chats/$userId': typeof AppChatsUserIdRoute
  '/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/chats/': typeof AppChatsIndexRoute
  '/groups/': typeof AppGroupsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/profile': typeof AppProfileRoute
  '/videos': typeof AppVideosRoute
  '/': typeof AppIndexRoute
  '/chats/$userId': typeof AppChatsUserIdRoute
  '/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/chats': typeof AppChatsIndexRoute
  '/groups': typeof AppGroupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/videos': typeof AppVideosRoute
  '/_app/': typeof AppIndexRoute
  '/_app/chats/$userId': typeof AppChatsUserIdRoute
  '/_app/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/_app/chats/': typeof AppChatsIndexRoute
  '/_app/groups/': typeof AppGroupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/videos'
    | '/chats/$userId'
    | '/groups/$groupId'
    | '/chats/'
    | '/groups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/profile'
    | '/videos'
    | '/'
    | '/chats/$userId'
    | '/groups/$groupId'
    | '/chats'
    | '/groups'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/profile'
    | '/_app/videos'
    | '/_app/'
    | '/_app/chats/$userId'
    | '/_app/groups/$groupId'
    | '/_app/chats/'
    | '/_app/groups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/videos': {
      id: '/_app/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AppVideosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/': {
      id: '/_app/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AppGroupsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chats/': {
      id: '/_app/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AppChatsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/$groupId': {
      id: '/_app/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AppGroupsGroupIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chats/$userId': {
      id: '/_app/chats/$userId'
      path: '/chats/$userId'
      fullPath: '/chats/$userId'
      preLoaderRoute: typeof AppChatsUserIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppVideosRoute: typeof AppVideosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChatsUserIdRoute: typeof AppChatsUserIdRoute
  AppGroupsGroupIdRoute: typeof AppGroupsGroupIdRoute
  AppChatsIndexRoute: typeof AppChatsIndexRoute
  AppGroupsIndexRoute: typeof AppGroupsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppVideosRoute: AppVideosRoute,
  AppIndexRoute: AppIndexRoute,
  AppChatsUserIdRoute: AppChatsUserIdRoute,
  AppGroupsGroupIdRoute: AppGroupsGroupIdRoute,
  AppChatsIndexRoute: AppChatsIndexRoute,
  AppGroupsIndexRoute: AppGroupsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
